#!/bin/sh
#
# commafeed        init file for starting up the commafeed daemon
#
# chkconfig:   - 20 80
# description: Starts and stops the commafeed daemon.

# Source function library.
. /etc/rc.d/init.d/functions

name="commafeed"
exec="/home/applis/commafeed/bin/startup.sh"
pidfile="/var/run/commafeed.pid"


lockfile=/var/lock/subsys/commafeed

start() {
    [ -x $exec ] || exit 5
    echo -n $"Starting $name: "
    daemon --user ${COMMAFEED_USER-tomcat} "$exec"
    retval=$?
    echo
    [ $retval -eq 0 ] && touch $lockfile && pgrep -f $name > $pidfile
    return $retval
}

stop() {
    echo -n $"Stopping $name: "
    daemon --user ${COMMAFEED_USER-tomcat} "/home/applis/commafeed/bin/shutdown.sh"
    retval=$?
    echo
    [ $retval -eq 0 ] && rm -f $lockfile
    return $retval
}

restart() {
    stop
    start
}

reload() {
    false
}

rh_status() {
    status -p $pidfile $name
}

rh_status_q() {
    rh_status >/dev/null 2>&1
}


case "$1" in
    start)
        rh_status_q && exit 0
        $1
        ;;
    stop)
        rh_status_q || exit 0
        $1
        ;;
    restart)
        $1
        ;;
    reload)
        rh_status_q || exit 7
        $1
        ;;
    force-reload)
        force_reload
        ;;
    status)
        rh_status
        ;;
    condrestart|try-restart)
        rh_status_q || exit 0
        restart
        ;;
    *)
        echo $"Usage: $0 {start|stop|status|restart|condrestart|try-restart}"
        exit 2
esac
exit $?
